### PR TITLE
do not depend on nose

### PR DESCRIPTION
**Pull request by pgajdos**
Use pytest's raise instead of nose's assert_raise. nose is deprecated, will not work with future python versions.

### CODE REVIEW

**Comment by bashtage** [comment]
While I support this patch, you might want to see if formulaic might suit your needs.  I think patsy is mostly in EOL mode.

**Comment by pgajdos** [comment]
It seems that few packages in openSUSE still require python-patsy:
   python-ggplot
   python-seaborn
   python-statsmodels

**Comment by bashtage** [comment]
seaborn needs it because of statsmodels IIRC. statsmodels is considering whether formulaic can become the formula parser.

ggplot is abandoned without a commit in 4 years. plotnine is the preferred grammar for graphics in Python.

**Comment by bashtage** [comment]
An alternative fix (and more standard) would be to pull all of the tests out of code files into test files so that nose isn't needed to run patsy.

**Comment by pgajdos** [comment]
> seaborn needs it because of statsmodels IIRC. statsmodels is considering whether formulaic can become the formula parser.
> 
> ggplot is abandoned without a commit in 4 years. plotnine is the preferred grammar for graphics in Python.

Thanks for letting me know. I just go trough python modules that still use nose and try to fix them, without not much knowledge about the context.

**Comment by pgajdos** [comment]
> An alternative fix (and more standard) would be to pull all of the tests out of code files into test files so that nose isn't needed to run patsy.

@bashtage, I am not sure I understand. Of course it would be better to have them tests in separate test files, but you use assert_raises, so you will have to youse nose anyway, no?

Anyway, it seems that travis does not like me today, so let's try later.

**Comment by pgajdos** [comment]
Closing for now.

**Comment by bashtage** [comment]
Normally projects have directories that look like

root\patsy
root\patsy\tests
root\setup.py

and then in root\patsy\tests you have files that are named `test_<something meaningful>.py`.  Under normal execution files under root\patsy\test are not executed, and so are only picked up by the test runner, e.g., nose.  This means that patsy will be importable under Python 3.9 even if nose it not. It won't be testable though.

**Pull request closed without merging**
