### PR TITLE
Fix for unnecessary prepending default column name. Closes #54.

### LINKED ISSUE #54: Tests fail with latest Pandas (0.15.2)
With NumPy 1.9.1, Pandas 0.15.2, and Patsy 0.3.0:

```
$ nosetests
............./usr/local/lib/python2.7/dist-packages/pandas-0.15.2_182_gbb9c311-py2.7-linux-x86_64.egg/pandas/core/c
ategorical.py:462: FutureWarning: Accessing 'levels' is deprecated, use 'categories'
  warn("Accessing 'levels' is deprecated, use 'categories'", FutureWarning)
/usr/local/lib/python2.7/dist-packages/pandas-0.15.2_182_gbb9c311-py2.7-linux-x86_64.egg/pandas/core/categorical.py
:414: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  warnings.warn("'labels' is deprecated. Use 'codes' instead", FutureWarning)
...FF.................
======================================================================
FAIL: patsy.test_highlevel.test_formula_likes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/whelchel/patsy-0.3.0/patsy/test_highlevel.py", line 202, in test_formula_likes
    [[1], [2], [3]], ["x"])
  File "/home/whelchel/patsy-0.3.0/patsy/test_highlevel.py", line 104, in t
    expected_lhs_values, expected_lhs_names)
  File "/home/whelchel/patsy-0.3.0/patsy/test_highlevel.py", line 32, in check_result
    assert rhs.design_info.column_names == expected_rhs_names
AssertionError

======================================================================
FAIL: patsy.test_highlevel.test_return_pandas
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/whelchel/patsy-0.3.0/patsy/test_highlevel.py", line 348, in test_return_pandas
    assert np.array_equal(df4.columns, ["AA"])
AssertionError

----------------------------------------------------------------------
Ran 35 tests in 54.269s
FAILED (failures=2)
```

### PR DESCRIPTION
**Pull request by PashaPodolsky**
There was unconditional adding prefix, I'd added checking if column name is digit and only therefore prepend default name. It has lead to passing all tests.

### CODE REVIEW

**Comment by njsmith** [comment]
Sorry, can you elaborate on what the purpose of this is and in what circumstance you find yourself needing it?

(Also it will need a new test, even if it passes all the old ones ;-).)

**Comment by PashaPodolsky** [comment]
Look at issue #54. Two tests with pandas were failing. I.e. even if we have columns having its own proper name, patsy would rename it by prepending 'x'. This fix limits this behaviour only for cases when column have no name.

**Comment by njsmith** [comment]
Oh, I see. I tried to fix this differently in a1211e5641cb75adf82948b983d437eb878a4595, let's see what the Travis tests think :-)

**Comment by njsmith** [comment]
Looks like it fixed those two tests at least (though there's still issues with pandas's redo of the Categorical stuff, sigh). Anyway, closing this -- please re-open if there's remaining stuff here.

**Pull request closed without merging**
