### PR TITLE
TST: Use pytest as the test runner

### PR DESCRIPTION
**Pull request by bashtage**
Switch to pytest
Remove testing of legacy Python versions < 3.6

### CODE REVIEW

**Comment by bashtage** [comment]
xref #163

**Comment by bashtage** [comment]
@njsmith Do you have any thoughts on trying to move to pytest?  This PR runs the same tests with more-or-less the same coverage.

**Comment by matthewwardrop** [comment]
Hi @bashtage and @pgajdos ; moving to `pytest` makes eminent sense; and since we are more or less in a feature freeze now removing legacy versions makes sense. I'll take a closer look at this PR and #163 shortly. Neither drops `nose` entirely, and have somewhat complementary changes. I will likely end up synthesizing these changes together with my own, and give the appropriate credit.

Thanks for these patches!

**Comment by matthewwardrop** [comment]
Closed by #178. Thanks so much for your patches.

**Pull request closed without merging**
