### PR TITLE
Fix: Add compat code for pd.Categorical in pandas>=0.15

### PR DESCRIPTION
**Pull request by JanSchulz**
pandas renamed pd.Categorical.labels to pd.Categorical.codes. It's
also now possible to have Categoricals as blocks, so Series can contain
Categoricals.

### CODE REVIEW

**Comment by kousu** [comment]
So just to be clear, I'm *not* supposed to be getting this "datatype not understood" exception, am I?

code.py
```
import pandas
import scipy.linalg; import scipy.lib.lapack.calc_lwork; scipy.linalg.calc_lwork = scipy.lib.lapack.calc_lwork #version creep bug: https://github.com/statsmodels/statsmodels/issues/2191
import statsmodels.api as sm #<-- this is the mark of a badly designed API: when you have a special subpackage just for your API

D = pandas.read_csv("surgery.csv", skipinitialspace=True)

def factor(series):
  "coerce series to a categorical variable in one line"
  "meant to be like R's factor() command"
  series = series.astype("category")
  series.cat.set_categories(set(series), inplace=True)
  # ^ from http://pandas-docs.github.io/pandas-docs-travis/categorical.html#getting-data-in-out
  return series

for C in ["treated", "risk"]:
  D[C] = factor(D[C])
```

With this setup, I either get:
```
In [10]: M = sm.GLM.from_formula("died ~ C(treated)", D)
---------------------------------------------------------------------------
PatsyError                                Traceback (most recent call last)
<ipython-input-10-27c4b7a47531> in <module>()
----> 1 M = sm.GLM.from_formula("died ~ C(treated)", D)

/usr/lib/python3.4/site-packages/statsmodels/base/model.py in from_formula(cls, formula, data, subset, *args, **kwargs)
    145         (endog, exog), missing_idx = handle_formula_data(data, None, formula,
    146                                                          depth=eval_env,
--> 147                                                          missing=missing)
    148         kwargs.update({'missing_idx': missing_idx,
    149                        'missing': missing})

/usr/lib/python3.4/site-packages/statsmodels/formula/formulatools.py in handle_formula_data(Y, X, formula, depth, missing)
     63         if data_util._is_using_pandas(Y, None):
     64             result = dmatrices(formula, Y, depth, return_type='dataframe',
---> 65                                NA_action=na_action)
     66         else:
     67             result = dmatrices(formula, Y, depth, return_type='dataframe',

/usr/lib/python3.4/site-packages/patsy/highlevel.py in dmatrices(formula_like, data, eval_env, NA_action, return_type)
    295     eval_env = EvalEnvironment.capture(eval_env, reference=1)
    296     (lhs, rhs) = _do_highlevel_design(formula_like, data, eval_env,
--> 297                                       NA_action, return_type)
    298     if lhs.shape[1] == 0:
    299         raise PatsyError("model is missing required outcome variables")

/usr/lib/python3.4/site-packages/patsy/highlevel.py in _do_highlevel_design(formula_like, data, eval_env, NA_action, return_type)
    150         return iter([data])
    151     builders = _try_incr_builders(formula_like, data_iter_maker, eval_env,
--> 152                                   NA_action)
    153     if builders is not None:
    154         return build_design_matrices(builders, data,

/usr/lib/python3.4/site-packages/patsy/highlevel.py in _try_incr_builders(formula_like, data_iter_maker, eval_env, NA_action)
     55                                        formula_like.rhs_termlist],
     56                                       data_iter_maker,
---> 57                                       NA_action)
     58     else:
     59         return None

/usr/lib/python3.4/site-packages/patsy/build.py in design_matrix_builders(termlists, data_iter_maker, NA_action)
    658                                                    factor_states,
    659                                                    data_iter_maker,
--> 660                                                    NA_action)
    661     # Now we need the factor evaluators, which encapsulate the knowledge of
    662     # how to turn any given factor into a chunk of data:

/usr/lib/python3.4/site-packages/patsy/build.py in _examine_factor_types(factors, factor_states, data_iter_maker, NA_action)
    422     for data in data_iter_maker():
    423         for factor in list(examine_needed):
--> 424             value = factor.eval(factor_states[factor], data)
    425             if factor in cat_sniffers or guess_categorical(value):
    426                 if factor not in cat_sniffers:

/usr/lib/python3.4/site-packages/patsy/eval.py in eval(self, memorize_state, data)
    483     #    http://nedbatchelder.com/blog/200711/rethrowing_exceptions_in_python.html
    484     def eval(self, memorize_state, data):
--> 485         return self._eval(memorize_state["eval_code"], memorize_state, data)
    486 
    487 def test_EvalFactor_basics():

/usr/lib/python3.4/site-packages/patsy/eval.py in _eval(self, code, memorize_state, data)
    466                                  self,
    467                                  self._eval_env.eval,
--> 468                                  code, inner_namespace=inner_namespace)
    469 
    470     def memorize_chunk(self, state, which_pass, data):

/usr/lib/python3.4/site-packages/patsy/compat.py in call_and_wrap_exc(msg, origin, f, *args, **kwargs)
    122                                  origin)
    123             # Use 'exec' to hide this syntax from the Python 2 parser:
--> 124             exec("raise new_exc from e")
    125         else:
    126             # In python 2, we just let the original exception escape -- better

/usr/lib/python3.4/site-packages/patsy/compat.py in <module>()

PatsyError: Error evaluating factor: TypeError: 'str' object is not callable
    died ~ C(treated)
```

or
```
In [11]: M = sm.GLM.from_formula("died ~ treated", D)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-ba4acccf7be6> in <module>()
----> 1 M = sm.GLM.from_formula("died ~ treated", D)

/usr/lib/python3.4/site-packages/statsmodels/base/model.py in from_formula(cls, formula, data, subset, *args, **kwargs)
    145         (endog, exog), missing_idx = handle_formula_data(data, None, formula,
    146                                                          depth=eval_env,
--> 147                                                          missing=missing)
    148         kwargs.update({'missing_idx': missing_idx,
    149                        'missing': missing})

/usr/lib/python3.4/site-packages/statsmodels/formula/formulatools.py in handle_formula_data(Y, X, formula, depth, missing)
     63         if data_util._is_using_pandas(Y, None):
     64             result = dmatrices(formula, Y, depth, return_type='dataframe',
---> 65                                NA_action=na_action)
     66         else:
     67             result = dmatrices(formula, Y, depth, return_type='dataframe',

/usr/lib/python3.4/site-packages/patsy/highlevel.py in dmatrices(formula_like, data, eval_env, NA_action, return_type)
    295     eval_env = EvalEnvironment.capture(eval_env, reference=1)
    296     (lhs, rhs) = _do_highlevel_design(formula_like, data, eval_env,
--> 297                                       NA_action, return_type)
    298     if lhs.shape[1] == 0:
    299         raise PatsyError("model is missing required outcome variables")

/usr/lib/python3.4/site-packages/patsy/highlevel.py in _do_highlevel_design(formula_like, data, eval_env, NA_action, return_type)
    150         return iter([data])
    151     builders = _try_incr_builders(formula_like, data_iter_maker, eval_env,
--> 152                                   NA_action)
    153     if builders is not None:
    154         return build_design_matrices(builders, data,

/usr/lib/python3.4/site-packages/patsy/highlevel.py in _try_incr_builders(formula_like, data_iter_maker, eval_env, NA_action)
     55                                        formula_like.rhs_termlist],
     56                                       data_iter_maker,
---> 57                                       NA_action)
     58     else:
     59         return None

/usr/lib/python3.4/site-packages/patsy/build.py in design_matrix_builders(termlists, data_iter_maker, NA_action)
    658                                                    factor_states,
    659                                                    data_iter_maker,
--> 660                                                    NA_action)
    661     # Now we need the factor evaluators, which encapsulate the knowledge of
    662     # how to turn any given factor into a chunk of data:

/usr/lib/python3.4/site-packages/patsy/build.py in _examine_factor_types(factors, factor_states, data_iter_maker, NA_action)
    427                     cat_sniffers[factor] = CategoricalSniffer(NA_action,
    428                                                               factor.origin)
--> 429                 done = cat_sniffers[factor].sniff(value)
    430                 if done:
    431                     examine_needed.remove(factor)

/usr/lib/python3.4/site-packages/patsy/categorical.py in sniff(self, data)
    169         # fastpath to avoid doing an item-by-item iteration over boolean
    170         # arrays, as requested by #44
--> 171         if hasattr(data, "dtype") and np.issubdtype(data.dtype, np.bool_):
    172             self._level_set = set([True, False])
    173             return True

/usr/lib/python3.4/site-packages/numpy/core/numerictypes.py in issubdtype(arg1, arg2)
    761     """
    762     if issubclass_(arg2, generic):
--> 763         return issubclass(dtype(arg1).type, arg2)
    764     mro = dtype(arg2).type.mro()
    765     if len(mro) > 1:

TypeError: data type not understood
```

surgery.csv:
```
"survived", "died", "treated", "risk"
12, 3,                "control", "low"
10, 2,                "treated", "low"
 6, 7,                "control", "medium"
10, 3,                "treated", "medium"
 3, 6,                "control", "high"
 8, 2,                "treated", "high"
```


Versions:
```
In [16]: patsy.version.__version__
Out[16]: '0.3.0'

In [24]: pandas.version.version
Out[24]: '0.15.2'

In [27]: sm.version.version
Out[27]: '0.6.1'
```

**Comment by JanSchulz** [comment]
This probably needs some more work: labels -> codes and levels -> categories...

Shoudl I redo the PR or what's the status?

**Comment by njsmith** [comment]
Sorry I lost track of this! (Just moved from Edinburgh to Berkeley and have been dropping a lot of balls :-(.)

At this point I am completely lost and confused regarding pandas's categorical changes. @JanSchulz: do you know what to do? Please send help!

**Comment by JanSchulz** [comment]
Updated, fixed all nosetest errors in the file, let's see if travis sees some more...

**Comment by JanSchulz** [comment]
The above error is probably still present :-(

**Comment by JanSchulz** [comment]
I opend a issue in pandas repo regarding the above problem with is

```
In[16]: s = pd.Series([1,2,3,1,2,3]).astype("category")
In[18]: np.issubdtype(s.dtype, np.bool_)
Traceback (most recent call last):
  File "c:\data\external\ipython\IPython\core\interactiveshell.py", line 3032, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-607a91e2a828>", line 1, in <module>
    np.issubdtype(s.dtype, np.bool_)
  File "C:\portabel\miniconda\envs\ipython\lib\site-packages\numpy\core\numerictypes.py", line 763, in issubdtype
    return issubclass(dtype(arg1).type, arg2)
TypeError: data type not understood
```

**Comment by njsmith** [comment]
Those interested in this PR should check out #59, which I think (hope?) replaces it.

**Comment by JanSchulz** [comment]
close, as #59 replaces this?

**Comment by JanSchulz** [comment]
Closing, as this in in #59

**Pull request closed without merging**
