### PR TITLE
use pytest instead of nose

### PR DESCRIPTION
**Pull request by pgajdos**
nose is not maintained and will stop working in future python versions. Use pytest as a replacement.

The build will fail, will try to sort out.

### CODE REVIEW

**Comment by pgajdos** [comment]
Builds that now fail require not available versions of python and/or pandas.

I do not feel brave enough to switch from nosetests to pytest call in .travis.yml coverage commandline, but it is not necessary until you do not build against newer pythons (especially when you feel patsy EOL as per https://github.com/pydata/patsy/pull/162#issuecomment-688831172).

**Comment by pgajdos** [comment]
Note that I run these tests with pytest (without nose available) in %check section without any issues. For coverage, probably something like pytest-cov would have to be installed.

**Comment by bashtage** [comment]
You should remove nose as a dependency and only use pytest to run the tests.

**Comment by matthewwardrop** [comment]
Closed by #178. Thanks so much for your patches.

**Pull request closed without merging**
